### ISSUE TITLE
[Feature Request] - Create “Hangar for Dummies” Page

### ISSUE THREAD

**Issue by tristengeven** [AmericanAirlines/Hangar#333]
### Pre-requisites:
- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find another request for the same or similar feature.

## Is your feature request related to a problem, or an open issue? Describe the problem, and if applicable, reference the issue.

Depends on #332 

## Describe the solution you'd like

Option 1: This could be a static html file that exists in the root of the project which can be clicked to open a more visually-intuitive guide through setting up the app.

Option 2: We could manifest this as a separately hosted site. It would use the same frontend workflow created in #331 , and at the bottom of this page they can download a zip of the app that we build for them, which should work out of the box. -CAVEAT: we would have to host this site somewhere. I don’t know if the devs want that, but it may be a really cool feature.

**Comment by SpencerKaiser** [comment]
I think we should leverage the UI we already have and simply check if the environment is `development`. At that point, all we'd require from devs is to:
1. Clone the project
2. Install dependencies with `npm i`
3. Copy + rename `.env.sample` as `.env` (it already includes the `NODE_ENV='development'` snippet

If you're on board, can you modify the description to mention modifying the existing UI instead of a separate HTML file or hosted site?

**Comment by johnkahn** [comment]
Instead of adding this to the UI as a part of the app, I think it should remain separate. We already have a GitHub pages site setup for this repo, we could just modify that to work for this. It's pretty out dated so just scrap what's there and make it this page for now.

https://github.com/AmericanAirlines/Hangar/tree/main/docs
https://americanairlines.github.io/Hangar/#/
